# This file was generated by GoReleaser. DO NOT EDIT.
class Ecctl < Formula
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"

  version "1.8.0"
  sha256 intel:        "4e4d4fc7c5e2b2acb7191a77e1c10261f5eeecd42418a205d957cafcdd7e2f6c",
         arm64_linux:  "4e4d4fc7c5e2b2acb7191a77e1c10261f5eeecd42418a205d957cafcdd7e2f6c",
         x86_64_linux: "4e4d4fc7c5e2b2acb7191a77e1c10261f5eeecd42418a205d957cafcdd7e2f6c"

  url "https://download.elastic.co/downloads/ecctl/#{version}/ecctl_#{version}_#{os}_#{arch}.tar.gz"
  desc "Elastic Cloud Control, the official Elastic Cloud and ECE command-line interface"
  homepage "https://github.com/elastic/ecctl"

  def install
    bin.install "ecctl"
    system "#{bin}/ecctl", "generate", "completions", "-l", "#{var}/ecctl.auto"
  end

  def caveats
    <<~EOS
      To get autocompletions working make sure to run "source <(ecctl generate completions)".
      If you prefer to add to your shell interpreter configuration file run, for bash or zsh respectively:
      * `echo "source <(ecctl generate completions)" >> ~/.bash_profile`
      * `echo "source <(ecctl generate completions)" >> ~/.zshrc`.
    EOS
  end

  test do
    system "#{bin}/ecctl", "version"
  end
end
